module.exports = {
    MIN_WORD_LEN: 4,
    MAX_WORD_LEN: 6,
    DEFAULT_WORD_LEN: 5,
    DEFAULT_SCORES: {
        '4': {
            '1': 0,
            '2': 0,
            '3': 0,
            '4': 0,
            '5': 0,
            '6': 0,
            failed: 0,
            gamesPlayed: 0,
            totalScore: 0,
        },
        '5': {
            '1': 0,
            '2': 0,
            '3': 0,
            '4': 0,
            '5': 0,
            '6': 0,
            failed: 0,
            gamesPlayed: 0,
            totalScore: 0,
        },
        '6': {
            '1': 0,
            '2': 0,
            '3': 0,
            '4': 0,
            '5': 0,
            '6': 0,
            failed: 0,
            gamesPlayed: 0,
            totalScore: 0,
        },
    },
    DEFAULT_GAME: {
        '4': null,
        '5': null,
        '6': null,
    },
}